apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: placeholder 
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
