apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAV89cdnKU+SJ6gzuiIm8bpTfV/JQq8nacPHTTvqDb9I7OF5UYwtptLbmqLGL18P5R5hyhYgnjRzrm8uDknBrwM1XvKaEd92rGMFMxvhVYRhil0LessVtMBHWic10RgJc8CGBtqyB7KR3i/ICxFzQ9RrxBo9csfuvyDdgpqEHRaVTyuUiace3TB+6MMsdKaje+ATNLB+f0bhAJcOahOeBNpL5jCgnaaGWtaAruvlEH/lHqvgeFgX/H+ntQ0PE0g941MMVQjDRrgTi8hoKCGYs5MYUeVXV1xViNFl/AehkRiS1AisnD33VzM9keiNb3OSefF3awzh/BOYtJIRubcpt+PUuW+lAdOnZemLzhPcythmBzACfJ4IRZ2V0eIbip2s97sXNBdQXmYpz9BaEKSm9PwasaTw2EJX+CJXnIy86KKH+sbRyNVtqRPfkxK/Nq53JHzzctPvcVP/h6A2hRAY1uOjB4Hu/xbj+ITKMIyKiR2DteinfpGa159IZSzdBJh/1Mr2xtF7kRAHxq3YvmapA+BThcMaA4QXfHjIi0u9N+IU2VrfXUgpQesjUJWhdZeZDMh4RCTjDOP7JC462PRNj7EDEa5VO2gPfZhacrxV63cuHlHXYW/35itB+FXFH6Aac4AzG6Iu8iSC6QIr0yTbe/QI/4RvhHvpyXz0kwC23x+8Us5drr3DDd+ozHbkcrHgnCDEL9WHWgTlCPimbttuVf0exAyJX+UH7N/1qpblYcx+LKoI8H9G5pl
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
apiVersion: v1
