---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgC/hgctBn9H9p+wn5AHUm2oH6YfTH7pv2xy4XTzumd68rpAkbaDAGRrmGHDR5okiRTh3LELFoLdztBkVocPc6xtavZzuRn++gFBKkxZ1xTem+B73/fLaQJLZR2GjxukrvLp42asNPl575t7gOJsjqt1SuNUgLvyWqn8Czac1uGhHtQFEuJrY+5rBZJwwZHe3xtqT6zoJ/6H53128gnvOU9gYf8L1qPKi43cC0TsP3Xr/lNjPHnwsUNdeBrNR9MtpVdibA1WDieTvQaZbKYv479B5oZOlhK5oeE2WFRTPAJkG+T7/HDOkA375XUoKlUjZKfeL10rpUm7Xa1T/WKUGuP8+2a+laIDe3Y3pA4w0Gur75DX1GaTjKJOnHhPoFaNy85Vy6Y9z5iiFr+GbpGuONLi23m8aqoLqQhOr3ZelmILSeQ0d8wD4MHlc9/OEV+U9i9AYDzBN+jEvC8ceTa/NjNAhkYVuhemuEw+7t4S+waMhaNGGp60otwB4PRR1/6b0+StuvVycHFoAwYNv9u6xUWhAZOpedT1NrTTT76Ue6j24uYQTh8HXit2sowPxmZJr+6i4MQZW6VZ/dH1TGBb7zlt/wdq6T4O9RRQLrkWG6JS6xzy3Zt43FD5TQYVPn0dt0hsz5eIb44N9+w1cspAjkADu0wA0FWFisjaCYdJa61RwE4zdoCTVs5FqKy5jMIR7JKDR4wu/K6QhlVdGPA=
  template:
    metadata:
      name: pihole
      namespace: pihole
