---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgAPkyNJpZgR6cXxw4w6bZGGjNYEJMFKRXyGdEeUARrNrewmr8dq6eMJIIF+rjhGFj04Ly853bkTfdvGU0GOaq7F17MMsVEEn541cZ5DVoeR6Xf5EOip152aVNVEfq8jYDJhI7vYgXsOibmuV1pEkTiVrkkiW+quugw5m/cPN6Qhk6/OF0rGrXslbu/zhNxNpB3YvuCfcGdX5ArqwgUZnKwymGjAv1n6hVzPVoWy5/99R22OgqnCFyqiElrlNn/SC/So6xpX2pBnEr+4A/6DAJY/6pRHK3cyrTjIR8Ap88zjjCWvG6WxBWHa1nMTkoQUtQBLhDffM1Fa5myL/IZUMm+NEPTqh/35DF2kbV5wir+0f3bSY0KJcmv5+PJ2ro8nuDRsoCbtWUH47bksKfkXE75EvmTrcgaUmtX8fANwLh//JuOuUB3thPPT7vBFFkBPgQCI7c47c5yQ09ealIvZMqGHIuVbyXg4eIgzS82/OyQ3j1oPiO49t2RZApFcEfBMrNyvlDYLym5IFtZNw3d4a+/kxyoz1f4LaOutYBgeMG2VQ0BxDq6iizKgXsHHPDuUvw8+01j/a+mjC/S8WltDkVSYb3ead2YoKXbERuxBbGMODBWBjTLx5dW2dlcnqJTxpoKHG4y5N3k9SdlqQB4KwLNj7Whx+OmW7AQThaqvtIOdsR7JXrzB+RyzPVP7M2ooKDE/5hJlFGT7JJqjxgk=
  template:
    metadata:
      name: pihole
      namespace: pihole
