apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik 
  namespace: ingress-traefik 
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik 
      version: "36.x"
      sourceRef:
        kind: HelmRepository
        name: traefik 
        namespace: ingress-traefik 
      interval: 12h
  values:
    service:
      enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: "traefik-local"