apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/pihole
  - ../base/speedtest
  - ../base/immich
patches:
  - path: ./pihole/patches/secret.yaml
    target:
      kind: SealedSecret
      namespace: pihole
  - path: ./immich/patches/database-user.yaml
    target:
      kind: SealedSecret
      name: database-user
      namespace: immich