apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pg-operator 
  namespace: pg-operator 
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg 
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: pg-operator 
        namespace: pg-operator 
      interval: 12h