---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole 
spec:
  encryptedData:
    WEBPASSWORD: AgCV9AfmpSOvWfV1Y7N18qL0z0rXR9biRiEmuz+RbkFqHNt/pEIkj2egBb/ylHaZCvLYAa2Sn0IGQLPfXJRzfpp9Cqj47nbcijRNeCFswH2uriwwzOoNkAOWYRnyO4TqvLNUJC7tN56VGNzZbJQIgyz/PFLZPLqfEMMB6j+k7r3YRLmgD5zd4vsrvna+WNG+21u0kS4+O9xVfEtpS2elY8vBCtFVkNKKMN2QMiZojr+UDEIRkbkl60UlNekOhZP6RbnPx/amcJh3VCviRgCkdDLNWy6d4Q1OFXha27eXtQ0wsvNBBt0pbHRgYh/vgkH5D8lkVFSCueWAwQLP9ZwZ49rwbmUbZTk8h0eFs41t+ZjwmUDlndTx4cKIOxSsl6eIAYnOC5EInJ/Mp2hKJXtQ83gtJi6IeLwNZWHqI3W8aegW7Kqn1azw+uwCvjqOYVZ83XKTC2OvcrUj79zTvPWlKqpJd8g13Z+fkhGM+lkF99Rk7199erVtn2IeuuAg7amnN9klkVQ0LU3u0FEdEyhmBIOz3uOHHM8HKvRTKy4F+4zZ+O6I2ERy2HHlMJrve5gQPP49sMnTvvqxJNixtpUlI/KRfRB0TtYmh1uFZMDitEjug7zLenjEFdScgDv+Ckl0WCzGS7xwhm+NBI+SqNA3py8O4Ucw0ME7T6k8fYct2Vlo0+nH5Uq41mZ1ORm0tbK/GxA4KU2WFIDI
  template:
    metadata:
      name: pihole
      namespace: pihole 
