---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  encryptedData:
    app_key: AgAT/4wXc31KHNIzWjFVTJzVqLC8UhG3RksFA2zRqhMbqZy6jsSaBbDXhfhsb8mdElGOsIE4DQUMZQYMjE53qxunFJzpzroEyozEPQj82hWUBJdwtwsx8YrSI1qf/fgCC12E9Z/p2pEuOpSR5jOKpb5cI/7agz/4e3L6JjqGGK92MGLFB+pK1bBSlF7K7UDUpOwwkQ+qEBnwrhP9QyddCvc+bEpMmvfR815DyMTwJ8xE3VJJUjAC/QCh3MrnhicAj4zHjc1iBqysmgLq6KRGgt/YrZyzJxgh0TAkmJYSWUpxQFjRIu5HDdFrc2i+Qsg+aeALhXhQD3P9p3Siaz6MInDAZH72m9fEwbUhvM10o+5G6SZv8eMoTuR5SfJQXogwlAi4E2uCvk6knbfCGSgEshh7bgFKNVall8sTnLs4VxmatceTj4y2LKXQg6CMZ8Q7fnu8bih2rdZh+azaWfhRMxN2MX5EXRyimkbOiMRlV5aSzCDfbEGDUKx8ogtEP1RJpimf9J+4xd7AKoQX1EC8QAarIxAszBOHbyjznjMYYmE3knsVh2iZ4vI2tpIDdiG/4lfYPeaBcrlL8iDWAa6vQTY0sYbR4CS6EXoiKhhAXbgBnj0CT23T1oOY7AO9SS/f12oAa6nVIPxj77zh8LcXRr/IrWwQvV05qQb4q/XMCKuPiyGI/DRjFGIVAkxkJ+9aC1WeNCBAkm67Udx2BRR/jUkzcqlL05GKptgvmRYibnz8jkzYMqgn1glQl83XxK5XBDU7Yqg=
  template:
    metadata:
      name: speedtest
      namespace: speedtest
