---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  encryptedData:
    app_key: AgDfxOqAGQXY8H3KV9PbA/yVVHH9FUiHESYRYx8w5XzaxDM4Tjn6VwCuvugwgd2mJiigrGt5yrJ6e8urEtA1Qmd1MZRBSiNCE0sX72AYR0UxVq6vhrtlEnBmIkcFU04SPJ/3rqEfG+TH8bc752HXg0PjlDBY11QP7vkcyEcJC7P97XGB3S9ixaosSiKRGqC67QXBM22CcCvQpgCHj3CsIufdYRrRWcdBOZXk3IvS1Yox57UZEipeqCSJVih1b/tOUoifnbpQijh40LnsG3cg8LVxJOqYp+KV7u8wZEQ4peAaF90zdtvPPnCgBpu9Dbv2FCPsTRlkE4KCxgXYKT9DlZ7sVXaBdALnpAzSqVSDlX8v4hXV52PYQVZd5uO4sTTCEH+Dn3jBCjHrBjVo1nadLfTHbkdn2ahaklvoWAO0CgARhyP/Xa1mMJWs9cDM8Ue04BfUUxSMIah2pqlW1SzrVbKk8fYRUMkYM+sW0M6IRIBsCdccnhv7/Njto8mFgEeri4L5uxEws/F/G4ghW49t/TT9OF1Yu3DHyFUovExcYLRQnBNqX2F4j9UhIp4TAHO6j7PTw4N/1bfKZhuUxOs+RddXb5lw5qZMcjL/1cphJ0w50E5IC9bKbMceqJcCFA3vSv8j2zw8DIzlj+5VWg+szuX2ITgFrkkOxmx8frhqe2RKeR76a4c93ocpPiVL1I1Lu54FVBkZDgqX9LQKFGudG6Tbcu+AbYG0kyf7DF4+66Mdx4KQPiTyeyIKhzG71V+98gb2t9wY2tdFzzlqt159hnDGyZ5hqQ==
  template:
    metadata:
      name: speedtest
      namespace: speedtest
