---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  encryptedData:
    app_key: AgC+nFn9ocFlrcSg5/r+pPytrmJ+JpkQhg/p5WgRpnvGNPB0aHAvaqlL1jmaEqKkJ/ZCQ7fHZ0RbrAiljNpALx3fWF0SITWNMExAWHF9Jv6dwj+oj70/Cp6zQbHzIJkCek4RDCX1Kf/flaNQOhamx5nrBDGy+aHfwRLmJfVeIl8MHfkKoaT+tb4st2R2JiEsl/KdYsh/w+BmRoW/mguywpvxQ2QuSfYAYZJ0oLleIGux6nbfMKIwsPM4giuxnlW6C9UzBB9e8RJeWsSXkVRN1HHb0Sapxy6bysFMhJYeDVD8P8sgRbc3te0TW916WwFFJ2EEfakHu8fpbOBb5bcQzFTWZ1DFIb9WhguDRWK5H96+9l33x4iWkrpp4GiygSu0j2zBzKOdedU89RCNQJUIKi2x2gvEu6jQANeFtUBeR8zJxRq5s466kzCxWSJ7GOsvPIKyrBtrU2lBmt2JWZrl42XaClGeomeSwrtRpULBEzVLoFAlLxGmYF+MdZYRGWEjape6NGNIuIfcUoQFT3L0UrdeOy1kmJxI0Kyws28QiajqWx41glkelCXh0AN5fMZMnqXj5LUnZmfpJ2sqXFCxd7l+RU0ycUqz7+idsNPUG6Sn9jOlNtpxwQR8yIvFk/BuZ9mRs5iQWqbWktioKDZ8tsS0TAtJ39soGWapA2DNxWNUhFCWsjuwqByS35p0YhS9x6kGVhyROngFDl2Q32ABXGQPCtYsuBpAeY2k45hdsjvnc9jiYMPLq7TEHKI0Kzih8RTd4iQcj3FLU1JCQVXTm3HM6e3RYw==
  template:
    metadata:
      name: speedtest
      namespace: speedtest
