---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest
  namespace: speedtest
spec:
  encryptedData:
    app_key: AgCbufCMp7JEK35Zvx8+bbZro8cda1HLKHbuow5YFWob0WYDiyB4BfxKQaqzPbqxmkD7qCZC50Hp7JfHb3ZwVo/JNA1LkFclDeK4y4mWRWdb6PLPiuEpUzkJCkD8x92ZKl/dEoZo+NczqnAWzly0cxN7+xAftONscXTrVO3oceyPscTlo2k275WORpbSmzivTYmVn4Y7UoRVkxjheX6XsqN1TOArSSfrrZXLywQKJU4EH0I0E84bip9rR6H82uzshlkca0KzkZs//X5yNIxXf6vqlEW2mo4rXDZCfcqnLdQXdA/uoPJ1RBr8kbFzfJaclh0LFhDQGuWYlN5ApkkNOXkcuKl2DGDuSk0mNTUeyvGkSS4HyyvcbvPFmtRAyLZ1Lk69HmjS/QbyCTfJCLK8CLPdB0+rWUnN8bkohCPRd6B5ZoCtOmxqS+YNisVMKl2TFC8lUzOSyYTlGclP9b/LOu5vEm/8BK4OboHZ7Byhp6wqp32b9rp45QUyg6E4++GFY0dKWb4vopmibCGov8XMJyQdqdo/BuVm3Au7oFzL43omH4meUdj+ucJxoxQYrkSs4lJjRXZLm7PlkaFJaGO0dEZXTOqxXiJQdg5U75lDe9A3wYBaYoJmj94bZECwrKXtyCfg4KErIo+Jl5ub93qq6l6OoficavM6S4N6mOZslmj4xjIzE25Cr36maHYFxP8Bj4rJvhPebpu30F2kVdSCJi++QYji33bMdUV30znltjVn8rkTlVISefD6wadlsmXNxLTEj+g=
  template:
    metadata:
      name: speedtest
      namespace: speedtest
