apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster 
  namespace: immich
spec:
  description: "Immich cluster"
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba 
  instances: 1
  primaryUpdateStrategy: unsupervised

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: database-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    storageClass: longhorn-unsafe 
    size: 5Gi

