apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./volumes 
  - ./secrets
  - database-cluster.yaml 
  - repository.yaml
  - release.yaml
  - HTTPRoute.yaml