apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich 
  namespace: immich 
spec:
  chartRef:
    kind: OCIRepository 
    name: immich
    namespace: immich 
  interval: 10m
  values:
    postgresql:
      global:
        postgresql:
          auth:
            existingSecret: database-user
    immich:
      persistence:
        library:
          existingClaim: images
    env:
      DB_HOSTNAME: immich-cluster-rw
      DB_DATABASE_NAME: immich
    redis:
      enabled: true
    machine-learning:
      enabled: false
    server:
      ingress:
        main:
          enabled: false