apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich 
  namespace: immich 
spec:
  interval: 30m
  chart:
    spec:
      chart: immich 
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich 
        namespace: immich 
      interval: 12h
  values:
    postgresql.global.postgresql.auth.existingSecret: database-user
    env.DB_HOSTNAME: immich-cluster-rw
    env.DB_DATABASE_NAME: immich
    redis.enabled: true
    machine-learning.enabled: false
    server.ingress.main.enabled: false